/**
 * @ngdoc object
 * @name techTalk.models.newsModel
 * @description
 * user model factory
 *
 * @requires ex.breeze
 * @requires techTalk.models.newsModel
 *
 * @property {string} id the ID
 * @property {string} username the username
 */
angular.module('techTalk.models')
    .factory('newsItemModel', [
        'breeze',
        function(breeze) {
            var DT = breeze.DataType;
            var meta = {
                shortName: "NewsItem",
                namespace: "techTalk",
                defaultResourceName: "NewsItem",
                autoGeneratedKeyType: breeze.AutoGeneratedKeyType.Identity,
                dataProperties: {
                    id: { dataType: DT.Int64, isPartOfKey: true },
                    title: { dataType: DT.String },
                    summary: { dataType: DT.String },
                    body: {dataType: DT.String}
                },
                navigationProperties: {

                }
            };
            return meta;
        }
    ]);