/**
 * @ngdoc object
 * @name techTalk.models.userModel
 * @description
 * user model factory
 *
 * @requires ex.breeze
 * @requires techTalk.models.userModel
 *
 * @property {string} id the ID
 * @property {string} username the username
 */
angular.module('techTalk.models')
    .factory('userModel', [
        'breeze',
        function(breeze) {
            var DT = breeze.DataType;
            var meta = {
                shortName: "User",
                namespace: "techTalk",
                defaultResourceName: "User",
                autoGeneratedKeyType: breeze.AutoGeneratedKeyType.Identity,
                dataProperties: {
                    id: { dataType: DT.Int64, isPartOfKey: true },
                    username: { dataType: DT.String },
                    password: { dataType: DT.String },
                    loggedIn: {dataType: DT.Boolean}
                },
                navigationProperties: {

                }
            };
            return meta;
        }
    ]);